// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"initialize","status":true,"description":"","parameters":{}},
{"name":"mm_managers","status":true,"description":"","parameters":{}},
{"name":"mm_objects","status":true,"description":"","parameters":{}},
{"name":"mm_scenes","status":true,"description":"","parameters":{}},
{"name":"mm_sprites","status":true,"description":"","parameters":{}},
{"name":"mm_windows","status":true,"description":"","parameters":{}}
];
